name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Terraform Init
        run: terraform init

      - name: TFLint
        run: |
          tflint
        continue-on-error: false

      - name: Comment TFLint Results
        if: failure()
        uses: GetTerminus/terraform-pr-commenter@v1

        with:
          commenter_type: tflint

      - name: Terraform Fmt
        run: terraform fmt -check -diff
        continue-on-error: false

      - name: Comment Fmt Results
        if: failure()
        uses: GetTerminus/terraform-pr-commenter@v1

        with:
          commenter_type: fmt

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false

      - name: Comment Validate Results
        if: failure()
        uses: GetTerminus/terraform-pr-commenter@v1

        with:
          commenter_type: validate
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
