name: Security Scan

on:
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Block on tfsec failure
        if: failure()
        run: exit 1
